import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [
		'main.ts',
	],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/lang-javascript',
		'@codemirror/lang-html',
	'@codemirror/lang-css',
	'@codemirror/lang-json',
		'@codemirror/lang-python',
	'@codemirror/lang-php',
	'@codemirror/lang-java',
		'@codemirror/lang-rust',
	'@codemirror/lang-cpp',
	'@codemirror/lang-sql',
	'@codemirror/lang-yaml',
	'@codemirror/lang-xml',
		'@codemirror/lang-markdown',
		'@codemirror/lang-ruby',
		'@codemirror/lang-swift',
	'@codemirror/lang-csharp',
	'@codemirror/lang-clike',
	'@codemirror/lang-go',
	'@codemirror/lang-elm',
	'@codemirror/lang-shell',
	'@codemirror/lang-lua',
	'@codemirror/lang-css',
	'@codemirror/lang-graphql',
	'@codemirror/lang-vim',
	'@codemirror/lang-bash',
	'@codemirror/lang-javascript',
	'@codemirror/lang-typescript',
	'@codemirror/lang-objc',
	'@codemirror/lang-rust',
	'@codemirror/lang-sql',
	'@codemirror/lang-wast',
	'@codemirror/lang-d',
	'@codemirror/lang-antlr',
	'@codemirror/lang-stex',
	'@codemirror/lang-mathml',
	'@codemirror/lang-n',
	'@codemirror/lang-sol',
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

if (prod) {
	await context.rebuild();
}

export default context;